#!/usr/bin/env node

var fs = require('fs')
var config = require('pkg-config')('domesticate', { root: null }) || {}
var vendorified = config.vendorified || 'vendor.js'
console.log(':: vendoring to', vendorified)
fs.writeFileSync(vendorified, '', 'utf-8')
for (var s in config.scripts) {
  if (config.scripts.hasOwnProperty(s)) {
    var dontvendor = (config.scripts[s].dontvendor === 'true') || false
    if (!dontvendor) {
      var script = config.scripts[s].src
      var code = fs.readFileSync(script, 'utf-8')
      fs.appendFileSync(vendorified, ';(function() { /* vendorified ' + script + ' */\n', 'utf-8')
      fs.appendFileSync(vendorified, code, 'utf-8')
      fs.appendFileSync(vendorified, '}())\n', 'utf-8')
      console.log(':: vendorified', script)
    }
  }
}

/* vim: filetype=javascript tabstop=2 shiftwidth=2 expandtab */
